// Seed data for The Counselify

export const SEED_CONTRACTS = [
  {
    id: '1',
    name: 'Safaricom Distribution Agreement',
    counterparty: 'Safaricom plc',
    jurisdiction: 'Kenya',
    contract_type: 'Distribution',
    risk_score: 67,
    status: 'active' as const,
    effective_date: '2023-01-15',
    expiry_date: '2025-06-30',
    created_at: '2023-01-15',
  },
  {
    id: '2',
    name: 'Equity Bank Service Level Agreement',
    counterparty: 'Equity Bank Group',
    jurisdiction: 'Kenya',
    contract_type: 'Service Agreement',
    risk_score: 34,
    status: 'active' as const,
    effective_date: '2023-06-01',
    expiry_date: '2026-01-15',
    created_at: '2023-06-01',
  },
  {
    id: '3',
    name: 'MTN Uganda Supply Agreement',
    counterparty: 'MTN Uganda Limited',
    jurisdiction: 'Uganda',
    contract_type: 'Supply',
    risk_score: 82,
    status: 'review' as const,
    effective_date: '2022-12-01',
    expiry_date: '2024-11-30',
    created_at: '2022-12-01',
  },
  {
    id: '4',
    name: 'Twiga Foods Logistics Contract',
    counterparty: 'Twiga Foods Limited',
    jurisdiction: 'Kenya',
    contract_type: 'Logistics',
    risk_score: 45,
    status: 'active' as const,
    effective_date: '2023-03-15',
    expiry_date: '2025-03-20',
    created_at: '2023-03-15',
  },
  {
    id: '5',
    name: 'CRDB Bank Software License',
    counterparty: 'Crescent Retail Bank Limited',
    jurisdiction: 'Tanzania',
    contract_type: 'License',
    risk_score: 28,
    status: 'active' as const,
    effective_date: '2024-04-01',
    expiry_date: '2026-04-01',
    created_at: '2024-04-01',
  },
  {
    id: '6',
    name: 'Uganda Revenue Authority Tax Services',
    counterparty: 'Uganda Revenue Authority',
    jurisdiction: 'Uganda',
    contract_type: 'Government Contract',
    risk_score: 56,
    status: 'active' as const,
    effective_date: '2023-11-01',
    expiry_date: '2026-11-01',
    created_at: '2023-11-01',
  },
  {
    id: '7',
    name: 'Kenya Commercial Bank Partnership',
    counterparty: 'Kenya Commercial Bank Group',
    jurisdiction: 'Kenya',
    contract_type: 'Partnership',
    risk_score: 41,
    status: 'active' as const,
    effective_date: '2024-01-10',
    expiry_date: '2025-12-31',
    created_at: '2024-01-10',
  },
  {
    id: '8',
    name: 'Rwanda National Police Procurement',
    counterparty: 'Rwanda National Police',
    jurisdiction: 'Rwanda',
    contract_type: 'Procurement',
    risk_score: 71,
    status: 'review' as const,
    effective_date: '2024-02-01',
    expiry_date: '2027-02-01',
    created_at: '2024-02-01',
  },
];

export const SEED_REGULATORY_SIGNALS = [
  {
    id: '1',
    jurisdiction: 'Kenya',
    title: 'Kenya Data Protection (Amendment) Act 2025',
    description: 'New amendments to strengthen data protection requirements for businesses operating in Kenya',
    probability: 78,
    impact_level: 'high' as const,
    affected_obligations: ['Data Protection', 'Privacy', 'Compliance'],
    recommended_action: 'Review data processing agreements and update privacy policies',
    expected_date: '2025-Q1',
  },
  {
    id: '2',
    jurisdiction: 'Uganda',
    title: 'Uganda Tax Appeals Tribunal Reform',
    description: 'Restructuring of tax dispute resolution mechanisms',
    probability: 65,
    impact_level: 'medium' as const,
    affected_obligations: ['Tax Compliance', 'Dispute Resolution'],
    recommended_action: 'Update tax compliance procedures and dispute handling protocols',
    expected_date: '2025-H1',
  },
  {
    id: '3',
    jurisdiction: 'EAC',
    title: 'EAC Cross-Border Data Transfer Directive',
    description: 'Harmonized rules for data transfers between EAC member states',
    probability: 90,
    impact_level: 'critical' as const,
    affected_obligations: ['Data Protection', 'Cross-Border Operations', 'Compliance'],
    recommended_action: 'Establish data transfer agreements compliant with EAC directive',
    expected_date: '2025-Q2',
  },
  {
    id: '4',
    jurisdiction: 'Tanzania',
    title: 'Tanzania Financial Services Act Amendments',
    description: 'Tighter regulations on lending and financial services',
    probability: 72,
    impact_level: 'high' as const,
    affected_obligations: ['Financial Services', 'Lending', 'Consumer Protection'],
    recommended_action: 'Review financial products and lending terms for compliance',
    expected_date: '2025-Q3',
  },
  {
    id: '5',
    jurisdiction: 'Rwanda',
    title: 'Rwanda Digital Economy & Cybersecurity Bill',
    description: 'Comprehensive cybersecurity and digital business regulations',
    probability: 85,
    impact_level: 'high' as const,
    affected_obligations: ['Cybersecurity', 'Digital Operations', 'Data Protection'],
    recommended_action: 'Conduct cybersecurity audit and update security policies',
    expected_date: '2025-Q2',
  },
];

export const SEED_COMPLIANCE_ITEMS = [
  {
    id: '1',
    category: 'Tax Compliance',
    title: 'VAT Filing - Kenya',
    due_date: '2025-11-15',
    status: 'in_progress' as const,
  },
  {
    id: '2',
    category: 'Annual Returns',
    title: 'Annual Returns Filing - Kenya',
    due_date: '2025-12-31',
    status: 'todo' as const,
  },
  {
    id: '3',
    category: 'Data Protection',
    title: 'Data Protection Impact Assessment - Uganda',
    due_date: '2025-10-01',
    status: 'todo' as const,
  },
  {
    id: '4',
    category: 'Employment Law',
    title: 'Employee Handbook Review - Kenya',
    due_date: '2025-09-30',
    status: 'done' as const,
  },
  {
    id: '5',
    category: 'Licensing',
    title: 'Business License Renewal - Tanzania',
    due_date: '2025-08-15',
    status: 'in_progress' as const,
  },
];

export const SEED_DOCUMENT_TEMPLATES = [
  { id: '1', name: 'Non-Disclosure Agreement (NDA)', category: 'Contracts', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '2', name: 'Employment Contract', category: 'Employment', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '3', name: 'Service Agreement', category: 'Contracts', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '4', name: 'Data Processing Agreement (DPA)', category: 'Data Protection', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '5', name: 'Supplier Agreement', category: 'Contracts', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '6', name: 'Terms & Conditions', category: 'E-commerce', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '7', name: 'Privacy Policy', category: 'Data Protection', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
  { id: '8', name: 'Partnership Agreement', category: 'Contracts', jurisdictions: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'] },
];

export const JURISDICTIONS = ['Kenya', 'Uganda', 'Tanzania', 'Rwanda', 'Burundi', 'South Sudan', 'Somalia', 'Ethiopia', 'DRC', 'Malawi', 'Zimbabwe'];

export const INDUSTRIES = [
  'Agriculture & Agribusiness',
  'Manufacturing & Industrial',
  'Trade & Commerce',
  'Financial Services',
  'Technology & ICT',
  'Construction & Real Estate',
  'Energy & Natural Resources',
  'Transport & Logistics',
  'Tourism & Hospitality',
  'Legal & Consulting',
  'Accounting & Audit',
  'Education',
  'Healthcare & Life Sciences',
  'Government & Public Administration',
  'NGOs',
  'Defense & Security',
  'Fintech & Digital Finance',
  'E-commerce',
  'Media & Entertainment',
  'Creative Economy',
  'Blue Economy',
  'Green Economy',
];

export const KPI_METRICS = {
  complianceScore: {
    value: 84,
    trend: '+3',
    status: 'healthy' as const,
  },
  activeContracts: {
    value: 47,
    expiringSoon: 6,
    status: 'warning' as const,
  },
  openRiskFlags: {
    value: 12,
    critical: 3,
    status: 'alert' as const,
  },
  deadlinesThisMonth: {
    value: 8,
    nextDeadline: 'Nov 15',
    status: 'upcoming' as const,
  },
};
